# Generated by Django 4.1.7 on 2023-04-10 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_username_socialloginplatform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialloginplatform",
            options={"verbose_name": "소셜 로그인 플랫폼", "verbose_name_plural": "소셜 로그인 플랫폼"},
        ),
        migrations.AlterModelTable(
            name="socialloginplatform",
            table="social_login_platform",
        ),
    ]
