# Generated by Django 4.1.7 on 2023-04-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='작가명')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가',
                'db_table': 'artist',
            },
        ),
    ]
