# Generated by Django 4.1.7 on 2023-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="order_number",
            new_name="order_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("결제 대기", "Payment Pending"),
                    ("결제 완료", "Payment Completed"),
                    ("배송 대기", "Shipping Pending"),
                    ("배송 중", "Shipping In Progress"),
                    ("배송 완료", "Shipping Completed"),
                    ("구매 확정", "Purchase Confirmed"),
                ],
                default="결제 대기",
                max_length=50,
                verbose_name="주문 상태",
            ),
        ),
    ]
